# Container image
# Stages
stages:
  - setup
  - build
  - test
  - deploy
  - release

# Cache npm modules and cypress binary
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# Setup jobs
install-dependencies:
  image: andreysenov/node-gyp
  tags:
    - changani
  stage: setup
  script:
    - npm ci --prefer-offline
  # Cache node_modules
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
      # - .npm
      # - cache/Cypress
  # Only run npm ci if package-lock has changed
  # only:
  #   changes:
  #     - package-lock.json

# Test jobs
unit-tests:
  image: node:lts-alpine3.14
  tags:
    - changani
  stage: test
  script:
    - npm run test:unit

# e2e-tests:
#   image: cypress/base:14.16.0
#   stage: test
#   script:
#     - npm run test:e2e

# Build jobs
build:
  image: andreysenov/node-gyp
  tags:
    - changani
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - node_modules/
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/

# Release new version
create-release:
  dependencies: []
  image: andreysenov/node-gyp
  tags:
    - changani
  stage: release
  variables:
    GL_TOKEN: $GL_TOKEN
  script: npx semantic-release
  only:
    refs:
      - main

# Deploy
deploy-to-dev:
  dependencies: []
  image: node:lts-alpine3.14
  tags:
    - changani
  stage: deploy
  script:
    - npm run deploy:dev
  only:
    refs:
      - develop

deploy-to-prod:
  image: node:lts-alpine3.14
  tags:
    - changani
  stage: deploy
  script:
    - npm run deploy:prod
  only:
    refs:
      - main

sonarqube-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  # only:
  #  - master # or the name of your main branch
