# Container image
image: andreysenov/node-gyp

# Stages
stages:
  - setup
  - build
  - test
  - deploy
  - release

# Cache node_modules
cache:
  paths:
    - node_modules/
    - .npm
    - cache/Cypress

# Cache npm modules and cypress binary
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# Setup jobs
install-dependencies:
  stage: setup
  script:
    - npm ci --prefer-offline
  artifacts:
    paths:
      - node_modules/

# Test jobs
unit-tests:
  stage: test
  script:
    - npm run test:unit

# e2e-tests:
#   image: cypress/base:14.16.0
#   stage: test
#   script:
#     - npm run test:e2e

# Build jobs
build:
  stage: build
  script:
    - npm run build:ci

# Release new version
create-release:
  stage: release
  variables:
    GL_TOKEN: $GL_TOKEN
  script: npx semantic-release
  only:
    refs:
      - main

# Deploy
deploy-to-dev:
  stage: deploy
  script:
    - npm run deploy:dev
  only:
    refs:
      - develop

deploy-to-prod:
  stage: deploy
  script:
    - npm run deploy:prod
  only:
    refs:
      - main
